# Generated by Django 5.2.11 on 2026-03-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('textbooks', 'Textbooks'), ('electronics', 'Electronics'), ('dorm_essentials', 'Dorm Essentials'), ('services', 'Services')], default='General', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
